config/routes.rb
Rails.application.routes.draw do
  get 'record/new'
  resources :fan_comments
  resources :reviews
  resources :authors
  resources :users
  resources :books
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'hello/index', to: 'hello#index'
  get 'hoge/piyo', to: 'hello#index'
  get 'hello/index'
  get 'hello/view'
  get 'hello/nothing'
  get 'hello/app_var'
  get 'hello/list'

  # 第4章
  get 'view/keyword'
  post 'keyword/search'
  get 'view/form_tag'
  post 'view/create'
  get 'view/form_for'
  get 'view/field'
  get 'view/html5'
  get 'view/select'
  get 'view/col_select'
  get 'view/group_select'
  get 'view/select_tag'
  get 'view/select_tag2'
  get 'view/col_select2'
  get 'view/group_select2'
  get 'view/dat_select'
  get 'view/col_radio'
  get 'view/fields'
  get 'view/simple_format'
  get 'view/truncate'
  get 'view/excerpt'
  get 'view/highlight'
  get 'view/conc'
  get 'view/sanitize'
  get 'view/format'
  get 'view/number_to'
  get 'view/datetime'
  get 'view/link'
  get 'view/urlfor'
  get 'view/new'
  get 'members/login'
  get 'view/linkif'
  get 'login/info'
  get 'login/index'
  get 'view/current'
  get 'view/detail'
  get 'view/mailto'
  get 'view/image_tag'
  get 'view/audio'
  get 'view/video'
  get 'view/path'
  get 'view/capture'
  get 'view/tag'
  get 'view/content_tag'
  get 'view/helper'
  get 'view/helper2'
  get 'view/helper3'
  get 'view/adopt'
  get 'view/provide'
  get 'view/multi'
  get 'view/relation'
  get 'view/download'
  get 'view/quest'
  get 'view/nest'
  get 'view/partial_basic'
  get 'view/partial_param'
  get 'view/partial_col'
  get 'view/partial_spacer'

  #ログイン
  root 'users#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # 第5章
  get 'record/new'
  get 'record/find'
  get 'record/find_by'
  get 'record/find_by2'
  get 'record/where'
  get 'record/keyword'
  post 'record/ph1'
  get 'record/not(/:id)' => 'record#not'
  get 'record/where_or'
  get 'record/order'
  get 'record/reorder'
  get 'record/select'
  get 'record/select2'
  get 'record/offset'
  get 'record/page(/:id)' => 'record#page'
  get 'record/last'
  get 'record/groupby'
  get 'record/havingby'
  get 'record/where2'
  get 'record/unscope'
  get 'record/unscope2'
  get 'record/none(/:id)' => 'record#none'
  get 'record/pluck'
  get 'record/exists'
  get 'record/scope'
  get 'record/scope2'
  get 'record/def_scope'
  get 'record/count'
  get 'record/average'
  get 'record/groupby2'
  get 'record/literal_sql'
  get 'record/update_all'
  get 'record/update_all2'
  get 'record/destroy_all'
  get 'record/transact'
  get 'record/enum_rec'
  get 'record/keywd'
  post 'record/keywd_process'
  get 'record/belongs'
  get 'record/hasmany'
  get 'record/hasone'
  get 'record/has_and_belongs'
  get 'record/has_many_through'
  get 'record/cache_counter'
  get 'record/memorize'
  get 'record/assoc_join'
  get 'record/assoc_join2'
  get 'record/assoc_join3'
  get 'record/assoc_join4'
  get 'record/assoc_includes'
  get 'record/attr'

  get 'search' => 'books#search'

  #demo
  get 'view/demo'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || 'Railbook' %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
　　<div class="d-flex flex-column flex-md-row align-items-center p-2 px-md-10 bg-white border-bottom shadow-sm">
　　　　<%= link_to "図書リスト", books_path, method: :get, class: "my-0 mr-md-auto font-weight-normal Editlink h2" %>
　　　　<nav class="my-2 my-md-0 mr-md-3">
 <%
=begin%>
 　　　　　　<a class="p-2 text-dark" href="#">Features</a> 
 <%
=end%>

  <br />
  <div class="search-form">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, value: @keyword %>
      <%= f.submit "検索" %>
    <% end %>
    </div>

　　　　</nav>
      <% if logged_in? %>
        <%= render 'users/logged_in' %>
        <%= link_to "ログアウト", logout_path, method: :delete %>
      <% else %>
        <%= link_to 'ログイン/登録', new_user_path, class: "btn bg-primary text-white" %>
      <% end %>
　　</div id="">
    <div class="contents-wrap">
　　<%= content_for?(:content) ? yield(:content) : yield %> 
    </div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted"></p>
      </div>
    </footer>
</body>
</html>

app/views/layouts/child.html.erb
<% content_for :content do %>
<img src="http://www.wings.msn.to/image/wings.jpg" />
<hr />
<%= yield %>
<hr />
Copyright 1998-2017, YAMADA,Yoshihiro
<% end %>
<%= render template: 'layouts/application' %>